### ISSUE TITLE
Server-set cookies don't appear in browser

### ISSUE THREAD

**Issue by zengabor** [bdkjones/CodeKit2#125]
The cookies I set in my server-side application are not set in browser. The CodeKit middle layer swallows them. (Only "ckrp_ypos" is set everytime.)

Tested with all combinations of the "httponly" and "secure" flags.

This is a big issue for me because I cannot even work with most parts of my application as I cannot authenticate. This makes CodeKit 2 not really usable for a local development environment which depends on cookies.

CodeKit Build 15860
Server: Google AppEngine dev_appserver.py
Project settings: "Use this external server for all requests" is ticked
Browsers tested: Safari 7.0.1, Chrome 31.0.1650.63

**Comment by zengabor** [comment]
My way of testing this:

Install:
1. Get and extract https://github.com/gaborlenard/ck2-redirect-cookie/archive/v1.0.zip
2. Get and extract http://googleappengine.googlecode.com/files/GoogleAppEngineLauncher-1.8.8.dmg
3. Start GoogleAppEngineLaucher and observe its miserable name
4. Choose File > Add Existing Application...
5. For "Path" select the directory where you extracted the code in Step 1
6. Make note of the value of the "Port" field which you will use in CodeKit
7. Click "Add"

Test it without and with CodeKit:
1. With the "ck2-redirect-cookie" selected in GoogleAppEnglineLuancher click "Run"
2. After its icon turned to green click "Browse"
3. Observe that the link and the button redirects to what they say
4. Observe that after the redirection a cookie with "last_redirect" is set
5. Do the above tests again after you added the application to CodeKit

**Comment by tombonez** [comment]
Having the same issue here with Wordpress:
![screenshot 2014-01-07 12 33 18](https://f.cloud.github.com/assets/967673/1858897/05968364-7798-11e3-9f4a-65b22edd11cc.png)

**Comment by sethta** [comment]
I can also confirm this. I just had the same issue as @tombonez with WordPress. You can't login to WP without cookies.

**Comment by guill3m** [comment]
I'm having the same issue here for a Ghost blog and a Symfony 2 application. Can't login to any of those two.

May be related in some way to #129 or a completely different issue?

**Comment by bdkjones** [comment]
Ah. I think I see what's happening here. The HTTP response headers from the external server's response are being overwritten when CodeKit forwards that response to the browser. This should be an easy fix; I'll get it done today.

**Comment by bdkjones** [comment]
Fixed in Beta 7. Will post that version tonight.

**Comment by zengabor** [comment]
Still broken in Beta 7 (Build 15888).

Tested multiple times, including shift-starting CodeKit and removing the config.codekit. Nothing helped. :(

**Comment by tombonez** [comment]
Still having the same Wordpress login issue as above in beta 7 too.

**Comment by bdkjones** [comment]
Mother of God.

**Comment by guill3m** [comment]
The same here with the Ghost blog.

And now the Symfony one (server via VM with Vagrant) won't even load the login page. [It worked great on beta 6, except that I couldn't login, but page refresh and style injection were working fine]

**Comment by shshaw** [comment]
I've been having Wordpress/cookie issues as well. 

Using MAMP as the actual server, the login form still returns the cookie error in beta 7, and pages of the site that were not the home page would return CodeKit's "Cannot communicate with external server" page.

Trying to debug this further, I set up a test site using just [Wordpress Skeleton](https://github.com/markjaquith/WordPress-Skeleton) and I can't even get past the "famous five minute WordPress installation process" using the CodeKit server.

When I go to _.local:5757_, I get the installation page. When I click "submit", I get redirected to _.local:5757/install.php?step=2_, but it's still the same page as before. The information isn't actually submitted. I can't tell if this is directly related to cookies or if it might be more related to #134.

If I go to MAMP's _localhost:8888_ URL, I get the same installation page and it submits correctly and creates the database.

Here's a zip of the Wordpress files, which is basically just a clone of the Wordpress Skeleton repo at this point. http://cl.ly/1v3x02012L3U The database itself is empty, so no SQL file is needed. Username/password should just be root / root

**Comment by bdkjones** [comment]
Fixed in Beta 8, which I will post late tonight.

**Comment by zengabor** [comment]
\o/ Fixed indeed.

**Comment by guill3m** [comment]
Fixed for me too.

Both the Ghost blog and the Symfony 2 app via VM and Vagrant are working great now.

:D
