### ISSUE TITLE
WordPress Cookie Issue in Beta 8

### ISSUE THREAD

**Issue by sethta** [bdkjones/CodeKit2#144]
This may be a continuation of issue #125, but as the creator of that issue said it was fixed, I figure I'd just create a new one.

WordPress is still seeing cookings, but there's an issue with being able to login still. It's like the cookies are being reset upon login so I can't go any further. I've uploaded a quick video to DropBox (https://db.tt/F7dNC40A), which shows the issue when working on my local server and then when I'm working on the CK preview.

Has anyone else had this problem? Is there anything else I should try besides the Shift-Open which I already did?

**Comment by bdkjones** [comment]
Hmm.

I can log into the Wordpress back-ends just fine with Beta 8 on my machine. So the question is, what's different about your site and setup?

Please zip the entire project and a dump of the mySQL database and post a link so I can download and test with them. If you would, please include the username and password for logging into the back-end, as I'll need those.

Additionally, what browser are you using? Have you tried with others? This is the latest version of Wordpress (not an older release)? What external server is hosting the site on your Mac?

**Comment by sethta** [comment]
I'm using WordPress 3.8 with Chrome 31.0.1650.63. I just checked Firefox and Safari and I had issues with those as 
well. I'm also using MAMP 2.2 (not Pro). I have modified MAMP to pull in multiple .conf files, one for each vhost, so I can work on multiple domains.

I just sent you the zipped site and sql dump through WeTransfer and here's the conf file:

```
<VirtualHost *:80>
    ServerName wsc-academy.dev
    ServerAlias wsc-academy.dev
    DocumentRoot /Applications/MAMP/htdocs/wsc-academy.dev/
    DirectoryIndex index.html index.php
    <Directory /Applications/MAMP/htdocs/wsc-academy.dev/>
        Options -Indexes +IncludesNOEXEC +FollowSymLinks
        allow from all
        AllowOverride All
    </Directory>
</VirtualHost>
```

**Comment by bdkjones** [comment]
Ah. I’m almost positive that’s the issue. 

Can you explain what you’re doing with Mamp in a bit less technical language? I don’t really know too much about vhosts and configuring for them.

**Comment by sethta** [comment]
Basically, I've turned my free version of MAMP into a Pro version. Instead of going with the normal http://localhost/, I have set the server to accept domain names, just as an actual online server would.

Then in my hosts file, I've set up my dev domain to point to 127.0.0.1, which is my machine and where localhost is pointed.

If you would like, I can make a copy of my MAMP and configuration, and then install MAMP, using the same site, and see if that makes a difference. I probably won't be able to get around to doing that until Monday evening though.

**Comment by sethta** [comment]
Just realized I named this caching issue, when it's a cookie issue. I've renamed the issue title.

**Comment by tombonez** [comment]
Getting the exact same issue here, I'll test this on my Wordpress boilerplate in the next half hour and if it still persists on a fresh copy I'll zip it up for you.

**Comment by bdkjones** [comment]
I'm going to attempt to recreate your environment over here so I can test it. 

Please send me a screenshot of the entry in your hosts file and give me a step-by-step to set up Mamp the way you've got it over there. Additionally, please tell me where you've got your website folder located on your drive

**Comment by tombonez** [comment]
Here's my starter boilerplate, no special MAMP Pro settings, just setup as ck.dev
https://dl.dropboxusercontent.com/u/9833165/ck.dev.zip

**Comment by sethta** [comment]
Here's a screenshot of my host setup. You can see the modification I've made to MAMP for the httpd.conf file with my virtual hosts on the left. I've highlighted the changes.

Then for each host, I've created it's own .conf file in a new directory called vhosts (which you can see as a finder window in the bottom right).

A screenshot for the .conf file of the project I sent you is at the top right. The file is saved in `/Applications/MAMP/conf/apache/vhosts/wsc-academy.dev.conf` and the actual website is located at `/Applications/MAMP/htdocs/wsc-academy.dev/`

The last step I do is modify my hosts file (bottom right) to include `127.0.0.1    wsc-academy.dev` and then I restart MAMP.

![screen shot 2014-01-11 at 8 13 49 pm](https://f.cloud.github.com/assets/220730/1895331/dc792972-7b26-11e3-88e6-f724f999b104.png)

**Comment by tombonez** [comment]
Download's now working: https://dl.dropboxusercontent.com/u/9833165/ck.dev.zip
The username and password are both admin btw.

**Comment by bdkjones** [comment]
@sethta Okay, I've got your setup duplicated over here and am staring at the Wordpress login screen. I need the username and password to attempt to log in.

**Comment by bdkjones** [comment]
I think I've got it figured out. In your project settings, you have this specified for the external server address:

```
http://wsc-academy.dev/
```

Remove the trailing slash and try:

```
http://wsc-academy.dev
```

I believe that's the issue. When I use the former address, the webpage at vdk.local:5757 doesn't even load. Safari just shows me a "too many redirects" error message. When I use the latter, I can log into the backend of your Wordpress site just fine after configuring my MAMP installation to exactly match yours. (I manually added a new admin user to the database rather than wait for the password for your username).

**Comment by bdkjones** [comment]
Fixed in Beta 11.

**Comment by tombonez** [comment]
Still not working here. FYI, removing the trailing slash in beta 11 showing an "External Server Error" and adding it makes the website work again, login's still not working though (using the provided project: https://dl.dropboxusercontent.com/u/9833165/ck.dev.zip (admin/admin)).

**Comment by bdkjones** [comment]
@tombonez I need a full walkthrough of _exactly_ how you've got your server set up, like @sethta gave me.

**Comment by tombonez** [comment]
It's the default MAMP Pro setup with a custom domain host:
![screenshot 2014-01-18 18 54 50](https://f.cloud.github.com/assets/967673/1947931/37096082-8072-11e3-9920-36fe2727bd07.png)

**Comment by tombonez** [comment]
This appears to be the same issue as #146 by the way.

**Comment by bdkjones** [comment]
This is a duplicate of #146.

Basically, Chrome is a bitch and is refusing the honor the `set-cookie` HTTP response header for a localhost URL. I'm trying to find a way to work around this and will post my progress in #146. Until then, use Safari to log into Wordpress --- it works just fine.
