### ISSUE TITLE
Worpdress admin login woes

### ISSUE THREAD

**Issue by smlombardi** [bdkjones/CodeKit2#146]
I can access my MAMP Pro WP site fine, and finally css refresh works.

However, if I try to sign into the admin, http://charizard.local:5757/wp-admin in Chrome 33 I get an error about cookies

![screen shot 2014-01-11 at 7 22 37 pm](https://f.cloud.github.com/assets/835148/1895233/3fc9eeaa-7b20-11e3-8c39-4cd5afaca4d1.png)

Eventually, it redirects to http://charizard.local:5757/wp-login.php?redirect_to=http%3A%2F%2Fcharizard.local:5757%2Fwp-admin%2F&reauth=1 and shows the login screen, but every time I try to enter user name and password, the page just refreshes and the form resets.

I did get it to work earlier in Safari 7.01.  The first time I tried it took a few minutes to get to the login screen, but then it logged in.

**Comment by bdkjones** [comment]
What is your Mamp setup? I need every single detail about it.

**Comment by smlombardi** [comment]
MAMP Pro 2.2.  Set to the default web ports (80, 443, 3306). PHP 5.5.3, cache off. Os 10.9, WP 3.8.

![screen shot 2014-01-11 at 7 34 08 pm](https://f.cloud.github.com/assets/835148/1895243/51de08c8-7b21-11e3-82f4-134e0fd24101.png)

![screen shot 2014-01-11 at 7 34 17 pm](https://f.cloud.github.com/assets/835148/1895249/80ee1d1a-7b21-11e3-9fe7-532a86859905.png)

Anything else?

**Comment by sethta** [comment]
Setup looks pretty much the same as what I have on mine, just mine's without the GUI from MAMP Pro. The weird thing is that I'm not getting the cookies are disabled message like I was with Beta 7, but my site's still acting like they are disabled (Issue #144).

**Comment by bdkjones** [comment]
Try using MAMP without the vhost. 

That is, just set MAMP to host the folder where your wordpress site exists. Then, update your Wordpress settings "siteURL" and "home" properties (in the WP_settings table within the database). Give that a shot and let me know if you can log in --- that's how I tested Beta 8 over here and I want to confirm that vhosts are the issue.

**Comment by sethta** [comment]
Hmmm... well, I'm not sure what the problem is now. Maybe I've got something weird with my site that has an issue with CodeKit. I just quickly cloned MAMP and fixed my httpd.conf file and then put only my main site in the htdocs directory and I get a redirect loop error:

```
This webpage has a redirect loop

LessReload
The webpage at http://seths-macbook-pro.local:5757/ has resulted in too many redirects. Clearing your cookies for this site or allowing third-party cookies may fix the problem. If not, it is possibly a server configuration issue and not a problem with your computer.
Learn more about this problem.
Error code: ERR_TOO_MANY_REDIRECTS
```

But, when I just go to localhost, I don't have the issue.

What are you setting the `home` and `siteurl` properties to? I've tried both http://localhost and http://seths-macbook-pro.local:5757.

**Comment by bdkjones** [comment]
home and siteURL needs to point to the webroot folder for your wordpress site. If you MAMP set to host that folder directly, then http://localhost:[port] would be the appropriate entry, where port is the port you're running MAMP on.

**Comment by smlombardi** [comment]
I have it set like this, which is how WP configures it on install:

![screen shot 2014-01-11 at 8 45 58 pm](https://f.cloud.github.com/assets/835148/1895399/bbd523f6-7b2b-11e3-8d9e-5047239db692.png)
![screen shot 2014-01-11 at 8 45 39 pm](https://f.cloud.github.com/assets/835148/1895400/bbd56a5a-7b2b-11e3-83eb-dfa770ccecfd.png)

**Comment by smlombardi** [comment]
I tried adding the port to wp-options, but I still get the dead login page, http://charizard.local:5757/wp-login.php?redirect_to=http%3A%2F%2Fcharizard.local:5757%2Fwp-admin%2F&reauth=1

**Comment by rpkoller** [comment]
I experience the same wp-admin login issue, but i am just running the non MAMP pro version

**Comment by smlombardi** [comment]
Just tried beta 9, no change, same behavior.

**Comment by shshaw** [comment]
I'm also unable to login to WP-Admin running regular MAMP. However, I don't get the Cookies message, it just redirects back to the wp-login page. I noticed in the URL variables, `redirect_to` is set to `localhost:8888` instead of the `.local:5757` address. Changing it manually does not help.

**Comment by smlombardi** [comment]
I usually get the cookie message the first time, then after that the page just reloads instead of logging in.

**Comment by bdkjones** [comment]
In your project settings, does your External Server Address end with a trailing slash? If so, remove the last slash. Give it another shot after that.

**Comment by bdkjones** [comment]
Fixed in Beta 11.

**Comment by smlombardi** [comment]
Not fixed for me, sorry.  Just tried beta 12.  Going to charizard.local/5757/wp-admin/ still gives send me to 

http://charizard.local:5757/wp-login.php?redirect_to=http%3A%2F%2Fcharizard.local:5757%2Fwp-admin%2F&reauth=1

 with the cookie error and the infinite enter password/refresh.

I tried it with a second, simpler WP site I have also in Mamp pro.  Same results.  Only way to get admin is to go around CK and simply go to sa.dev/wp-admin. I can send you this site too if it helps.

**Comment by bdkjones** [comment]
I need every single detail about your setup. Everything you can think of. This is working over here.

**Comment by smlombardi** [comment]
Here is the site, zipped up with its sql: https://dl.dropboxusercontent.com/u/67226/FileChute/sa-site.zip

email me for the admin username/pwd

What else can I provide you with?

**Comment by bdkjones** [comment]
@smlombardi I need a step-by-step walkthrough of what you set in Mamp Pro to host this project. Literally everything you clicked/typed/entered, etc. I need to make my copy of Mamp Pro match yours exactly.

**Comment by smlombardi** [comment]
Okay, this was only a week or so ago.
1. download wordpress 3.8, unzip into a folder inside my ~/Documents/Freelance/clientname folder
2. in MAMP pro, clicked on webstart to go to its phpMyAdmin page. Created a new user for localhost and checked the box to create a db for the user with all rights granted.  I used a the same thing for the user name, db name, and password.
3. inside the wp folder, edited wp config file to point to this db and users/pass
4. in Mamp pro, clicked the plus below the list of hosts of the main screen. For server name, used sa.dev.  Clicked "choose" and browsed to the folder I unzipped in step 1
5. In browser, went to the install page for wp and did the default choices.  Eventually, I am asked to log into wordpress.  I see the Dashboard.
6. in the dashboard I create a page named Home and go to "reading", set the homepage to "static page" and to this home page
7.  In permalinks, I select the "post name" option
8. In plugins, I have installed "Contact From 7", "Disable Comments", "Root-Relative URLs"
9. I upload a commercial theme and configure several of it appearance options
10. The theme installs the "Revolution Slider" and "WP Page Navi" plugins.
11. start adding content
12. dragged the folder from step 1 into CodeKit
13. set codekit to use external server, sa.dev, port 80

I have also tried disabling the plugins.  In the event that one made some irreversible change, I will go now an start a new site with the default theme and no plugins.  I'll report back.

**Comment by smlombardi** [comment]
OK, I just installed a new wordpress site, steps 1-5 above only.  Same issue. So there is nothing at all about how Wordpress is installed or configured.

Perhaps something in mamp, although I can't figure out what's non-vanilla.

**Comment by bdkjones** [comment]
If you go to http://sa.dev in your browser, you see the Wordpress site correctly served by Mamp?

**Comment by smlombardi** [comment]
Yes.  I see it ok at the bonjour address, too.  

Only issue I have at this point is **logging into** wordpress via the bonjour address.

**Comment by smlombardi** [comment]
I just created a new site codekit.dev.  I can add it to codekit and see it at charizard.local:5757.  
I cannot log into charizard.local:5757/wp-admin
I can log into codekit.dev/wp-admin

Is that just the way it is?

**Comment by bdkjones** [comment]
Use the web inspector. Do you see cookies set after attempting to log in to the admin area through CodeKit's address?

And no, that's not "just the way it is". That's why we do betas.

**Comment by smlombardi** [comment]
ok, after I try to log in, and the login page reloads:

![screen shot 2014-01-18 at 10 15 46 pm](https://f.cloud.github.com/assets/835148/1948829/13935cca-80b8-11e3-8faa-ad6697aba957.png)

**Comment by smlombardi** [comment]
I also see this

![screen shot 2014-01-18 at 10 17 35 pm](https://f.cloud.github.com/assets/835148/1948830/4aa851fc-80b8-11e3-9ed5-87b1c6081f1a.png)

**Comment by rpkoller** [comment]
Here beta 12 isn't working either. In Safari not at all. It is loading forever. While in Chrome i made it once into the admin interface of wp. But i got logged out after a few clicks. then when i retried i can't login anymore at all. but without any error message. i just see the wp-admin login panel again and again. Will investigate tomorrow. It's already 5:40 am over here. need some sleep first.

**Comment by rpkoller** [comment]
Ok after minutes loading in safari i finally got to the login dialogue. In safari i get instead again: 
![bildschirmfoto 2014-01-19 um 05 43 25](https://f.cloud.github.com/assets/1665422/1948897/4c662620-80c4-11e3-9cde-12e2478fc194.png)

**Comment by bdkjones** [comment]
You're using virtual hosts through Mamp Pro as well?

I believe the issue is related to the shortcuts Mamp Pro takes to set up virtual hosts. If I do it manually, following the steps outlined in @sethta's post in #144, it all works fine. Mamp Pro may not be setting the same options on the virtual hosts you're creating in the GUI.

**Comment by smlombardi** [comment]
MAMP pro also edits /etc/hosts, apparently.

**Comment by bdkjones** [comment]
Well, hours and hours invested in tracking this down and it turns out to be a dumb decision by Google: https://code.google.com/p/chromium/issues/detail?id=56211

They disabled setting cookies for any address that is not registry-controlled. That is, any address that maps to localhost or an IP Address will completely ignore `Set-cookie` in the HTTP response headers. That's why logging into Wordpress when viewing it through CodeKit's preview server works just fine in Safari and fails in Chrome. 

Wonderful. Now I get to spend a bunch of time trying to work around it. I hate Google.

**Comment by bdkjones** [comment]
There may not BE a workaround for this issue, so please confirm that you can log into the Wordpress admin area using Safari.

**Comment by smlombardi** [comment]
Yes, it works in Safari 7.01.

**Comment by shshaw** [comment]
If Chrome is blocking localhost from setting cookies, why does it work from MAMP's plain localhost address? Is it the redirection causing issues?

stephen.local:5757/wp-admin/ still won't let me in, but I just tested localhost:5757/wp-admin/; no issues logging in and the browser refreshing works just fine.

**Comment by bdkjones** [comment]
FIXED IT.

This was the issue --> http://openradar.appspot.com/15933483

Turns out, Chrome and Firefox do not adhere to the HTTP specification, which requires that any HTTP header be able to contain multiple values in a comma-separated list. Chrome and Firefox will only recognize the first cookie in a comma-separated list; they will discard all subsequent cookies. So this:

```
Set-Cookie: <cookie1>, <cookie2>, <cookie3>
```

Has to be transformed into this:

```
Set-Cookie: <cookie1>
Set-Cookie: <cookie2>
Set-Cookie: <cookie3>
```

In order for Chrome to work. Of course, Apple's low-level HTTP messaging code automatically combines cookies into a comma-separated list because that's allowed by the HTTP spec. There's no way to override that behavior. Fortunately, however, that part of OS X is open source, so I could see Apple's implementation. I took their code and rewrote it to pass each cookie with a separate header. Or, in more bombastic terms:

## I rewrote part of OS Freaking X to fix this bug.

**Comment by bdkjones** [comment]
Fixed, finally, in Beta 14.

**Comment by zengabor** [comment]
Just tested multiple cookies in Chrome and it works as expected. Thank you very much for this, Sir Jones.

**Comment by Horttcore** [comment]
@gaborlenard was any work for that required? I can't get it to work here. Even in Beta 15

**Comment by zengabor** [comment]
I tested it with my own application running under Google AppEngine dev_appserver.py
