### ISSUE TITLE
Issue with Sass output path

### ISSUE THREAD

**Issue by edwardsdesign** [bdkjones/CodeKit2#58]
CK does not honor my css output path under sass settings. When ever I try to set a custom output path CK will only write to the initial default setting of ../css.

I keep my sass directory out of the site root but still within the project root. This allows for version control but does not clutter the site root for ease when pushing to QA and production.

So my project structure looks like this:

localhost

> project name
> 
> > sass
> > webfiles
> > 
> > >  css
> > > 
> > > > site.css

However, whenever I try to set the output path to ../web/css CK keeps placing the css file and folder into the project root like this:

localhost

> project name
> 
> > _**css**_
> > 
> > > _**site.css**_
> > 
> > sass
> > webfiles
> > 
> > > css

I have tried every possible combination under the sass settings (including output to the same folder) and every time the css folder gets recreated using the default ../css.

I have also tried to set a different output folder under the defaults for new projects without any luck.

Setup:
OSX 10.9.1
Sublime Text 3
Apache on localhost

**Comment by edwardsdesign** [comment]
UPDATE:

I am able to manually set the output paths by right clicking on the file and selecting the output dir however CK2 still does not honor the default / per project sass language defaults for the output path.

**Comment by bdkjones** [comment]
Did you click the "sync" button to the right of the "Output Path" title in project settings after you changed your output path settings?

CK does not just automatically nuke your existing output paths and reset them as you type; that would be terrible. You need to click that sync button once you've made changes to have those changes applied to the files in the project.

**Comment by BabylonSix** [comment]
OS X 10.9.1
Sublime Text 3 (build 3059)

Don't know if it's related, so I'll just post it here,
under Stylus, I can't choose custom output path either, pressing the little sync icon actually reverts it to ../css
I'm trying to change the output path relative to project root folder => ./_css

Also, the pop-over with the word "done" wont disappear when "done" is pressed.

After playing with it some more, it finally changed the output path to ./_css
except it still creates a file called "./css" instead of "./_css"

Changing the name to something else altogether sometimes makes it jump between previous names already typed in, still outputs "css" though

**Comment by edwardsdesign** [comment]
Yes, I tried clicked the sync button to the right of the output path. I also tried to set a different output folder as the default setting for all projects, removed the project and closed CK2, deleted the config.codekit file for the project and reopened and recreated the project with no luck. The only way I can set a different output folder, that worked for me, was to manually set the output file location through the individual file's preference pane.

**Comment by bdkjones** [comment]
If this is a Compass project, you'll need to adjust the output path in the config.rb file.

Otherwise, this should be fixed in Beta 4.

**Comment by edwardsdesign** [comment]
This is not a Compass project and I am still having this issue in BETA 4.
- I tried the shift while launch to reset to defaults
- I have tried deleting my config.codekit file and adding the project folder back
- I have removed the project, set the default output file location and added the folder back

**Comment by bdkjones** [comment]
@babylonsix Do not use the `./` component to indicate a current path. That's definitely not correct. I don't understand what output path you're trying to reach. Please describe the structure in more detail.

**Comment by bdkjones** [comment]
@edwardsdesign Please take a screencast video of the entire process showing the issue and then post a download link here so I can take a look. Thanks.

**Comment by edwardsdesign** [comment]
Sorry but I was unable to add audio to the screen cast, I will explain my process here:

I am using CK2 Beta 5
1. I add a new project
2. I set the new file output path under the project's sass language settings
3. The new path is not reflected on the site.scss file
4. If I compile the file a new css directory is generated at the default CK2 location (../css)
5. I have to manually set the output path on the site.scss file itself for CK2 to generate the css file in the proper location

https://dl.dropboxusercontent.com/u/5343083/CK2/ck2-beta5-output-path-issue.zip

**Comment by bdkjones** [comment]
Ok. Please zip the project in question and post a download link here so I can debug with it on my end. Thanks.

**Comment by edwardsdesign** [comment]
I created a sample project with the same file structure.

I have set the project default sass output file location to ../web/css . When I close the project settings, after clicking the refresh icon to the right of the Initial output path title, the new default location is not reflected when select the site.scss file, the site.scss properties panel still points to ../css .

Here are the sample project files:
https://dl.dropboxusercontent.com/u/5343083/CK2/ck2-op-project-files.zip

**Comment by bdkjones** [comment]
Well, I'm an idiot. I used a `return` instead of a `break` in the Sass case of a `switch` statement. This is finally fixed in Beta 6.
