### ISSUE TITLE
AppEngine dev_appserver.py - HTTP header based redirect does not show up in URL bar

### ISSUE THREAD

**Issue by zengabor** [bdkjones/CodeKit2#67]
Although the app engine dev_appserver.py  sets redirect HTTP headers, the browser's url bar does not update, as if the original URL would be still valid.

E.g., x.local:5757/jump is called which is redirected by dev_appserver.py to x.local:5757/final. The server is performing a longer (2s) operation and the browser displays CK2's "External Server Error" page.

Another refresh shows the final page. I still see x.local:5757/jump in the browser but the displayed content is already x.local:5757/final.

Another refresh performs the redirection again and the URL bar is still not updated.

**Comment by zengabor** [comment]
Redirect is still broken in Beta 4.

Also, cookies don't work (maybe only secure cookies, didn't have time to test it at the moment).

Looks like custom servers like AppEngine may have many issues with CodeKit 2 or even be unusable, like Appengine. So, is there a way in CodeKit 2 to switch back to the old behaviour of CodeKit 1, which worked so perfectly with Safari and Chrome?

**Comment by bdkjones** [comment]
Please give this a try with Beta 5.

**Comment by zengabor** [comment]
Unfortunately it’s still reproducible with build 15825

Looks like I will have to stuck with CodeKit 1.9 :(

**Comment by bdkjones** [comment]
Do you have the "Use External Server for all requests" box checked?

**Comment by zengabor** [comment]
Just tested with Beta 6 after launching it with the Shift key down and re-adding the project from scratch, ticking "Use this external server for all requests".

Still broken. ):

It's just the URL bar. The server sends the 302, and the redirection happens, the new page is displayed correctly. But the URL bar still shows the address before the redirection. Note that this happens for both GET and POST requests.

**Comment by bdkjones** [comment]
Does this impact the page or its functionality in any way, or is it merely a cosmetic "the address in the bar isn't right" type of deal?

**Comment by zengabor** [comment]
Cosmetic

**Comment by bdkjones** [comment]
Please put together a small demo project that shows the issue, zip it, and post a download link here. I'll see if I can resolve it.

**Comment by zengabor** [comment]
Install:
1. Get and extract https://github.com/gaborlenard/ck2-redirect-cookie/archive/v1.0.zip
2. Get and extract http://googleappengine.googlecode.com/files/GoogleAppEngineLauncher-1.8.8.dmg
3. Start GoogleAppEngineLaucher and observe its miserable name
4. Choose File > Add Existing Application...
5. For "Path" select the directory where you extracted the code in Step 1
6. Make note of the value of the "Port" field which you will use in CodeKit
7. Click "Add"

Test it without and with CodeKit:
1. With the "ck2-redirect-cookie" selected in GoogleAppEnglineLuancher click "Run"
2. After its icon turned to green click "Browse"
3. Observe that the link and the button on the HTML page redirects to what they say
4. Observe that after the redirection a cookie with "last_redirect" is set
5. Do the above tests again after you added the application to CodeKit

**Comment by bdkjones** [comment]
Should be fixed in Beta 7, which now forwards the HTTP response headers from the external server correctly. Will post 7 later tonight. Please give it a whirl and make sure it works.

**Comment by zengabor** [comment]
Still broken in Beta 7 (Build 15888).

Tested multiple times, including shift-starting CodeKit and removing the config.codekit. Nothing helped. :(

I will now try to look at the headers to get a better understanding.

**Comment by bdkjones** [comment]
Inspect the response headers that get sent back from the server. The status code ought to be 302.

**Comment by bdkjones** [comment]
FINALLY fixed in Beta 8. 

The redirect response from the origin server is no longer handled automatically by the proxy server in CodeKit. The 30x response is sent to the browser, allowing it to respond and issue a new HTTP request for the resource.

**Comment by zengabor** [comment]
\o/ Works perfectly under Beta 8.

**Comment by thierrymichel** [comment]
I had the same issue with redirect() in CodeIgniter.
Everything works correctly now! ^^
