### ISSUE TITLE
Vagrant / Node.js / Express

### ISSUE THREAD

**Issue by devilskitchen** [bdkjones/CodeKit2#72]
I'm running a Vagrant setup, using VirtualBox as the default VM.
The codebase is coffee files, running on Express and nginx on Node.js.

'Express server listening on port 3000', but translates to localhost:3030.

Putting the external server path as localhost:3030 does load the site through CK2 using http://cm-mac-mini.local:5757, but won't reload automatically (changes do propagate when reloaded manually though).

The CK2 URL will also load on my iPad, but also does not reload automatically (changes do propagate when reloaded manually though).

Perhaps I'm doing something wrong, so I'll keep investigating.

**Comment by hlissner** [comment]
Question: does your server serve fully-formed HTML documents? I find that if the output is <head>-less, CK won't inject its auto-reload JS script links.

**Comment by devilskitchen** [comment]
The end output is fully-formed, yes. The templating system used is SWIG, which uses a common layout template containing the head elements.

**Comment by bdkjones** [comment]
Does your setup support Bonjour networking? If not, it will likely resolve itself in Beta 4.

**Comment by devilskitchen** [comment]
I honestly don't know, Bryan: maybe not since many of the machines are Windows. I'll continue testing...

**Comment by bdkjones** [comment]
This should be resolved with Beta 4. I need an update, please.

**Comment by devilskitchen** [comment]
Will download and test asap...

**Comment by devilskitchen** [comment]
**UPDATE:** I cannot test this feature as CodeKit 2 Beta 4 simply crashes and quits when I try to add any project. I have tried Shift-starting, and deleting the Preferences through the Terminal as outlined.

I have sent you an updated crash report.

This is on my home Mac Pro 2x2GHz, OS 10.7.5, 5GB RAM.

I won't be back in front of my work machine—Mac Mini, OS 10.9.1, 8GB RAM—until 01/01/14.

**Comment by bdkjones** [comment]
I need the crash report posted here, please. Emailing me anything is not good; I get so much email I can't keep it straight.

Also: please let me know if it's resolved in Beta 5 on your work machine. I may simply make CK 2 a 10.8+ app.

**Comment by devilskitchen** [comment]
@bdkjones : I can add projects on my work machine without CK2 crashing, but the refresh is still not working.

Project here (usual stuff about secrecy, etc., and please let me know when you've downloaded it so that I can remove it): https://www.dropbox.com/s/zchbn0ubwgmhb4u/guess2give.zip

**Comment by bdkjones** [comment]
Fixed in Beta 6.

**Comment by devilskitchen** [comment]
Aces—it works! You have no idea how happy this has made me...
